<div class="popup-window" id="menu-popup-main-grid-actions-menu-1065" style="display: block; position: absolute; left: 311.971px; top: 301.257px; z-index: 1200 !important; padding: 0px;"><div id="popup-window-content-menu-popup-main-grid-actions-menu-1065" class="popup-window-content" style="padding: 0px;"><div class="menu-popup" style="display: block;"><div class="menu-popup-items"><span title="Просмотреть лид" onclick="BX.Crm.Page.open('/crm/lead/details/1065/')" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Просмотреть лид</span></span><span title="Редактировать лид" onclick="BX.Crm.Page.open('/crm/lead/details/1065/?init_mode=edit')" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Редактировать лид</span></span><span title="Копировать лид" onclick="BX.Crm.Page.open('/crm/lead/details/1065/?init_mode=edit&amp;copy=1')" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Копировать лид</span></span><span title="Удалить лид" onclick="BX.CrmUIGridExtension.processMenuCommand(
					'CRM_LEAD_LIST_V12_MANAGER',
					BX.CrmUIGridMenuCommand.remove,
					{ pathToRemove: '/crm/lead/list/?action_CRM_LEAD_LIST_V12=delete&amp;ID=1065&amp;sessid=6904190d9f5dd43114183d352cf1e19e' }
				)" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Удалить лид</span></span><span title="Добавить лид в список исключений" onclick="BX.CrmUIGridExtension.processMenuCommand(
					'CRM_LEAD_LIST_V12_MANAGER',
					BX.CrmUIGridMenuCommand.exclude,
					{ pathToExclude: '/crm/lead/list/?action_CRM_LEAD_LIST_V12=exclude&amp;ID=1065&amp;sessid=6904190d9f5dd43114183d352cf1e19e' }
				)" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Добавить в список исключений</span></span><span class="popup-window-delimiter"></span><span class="popup-window-delimiter"></span><span title="Создание контакта, компании и сделки на основании лида" class="menu-popup-item menu-popup-no-icon menu-popup-item-submenu"><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Создать на основании</span></span><span class="popup-window-delimiter"></span><span title="Добавить новое событие" onclick="BX.CrmUIGridExtension.processMenuCommand(
					'CRM_LEAD_LIST_V12_MANAGER',
					BX.CrmUIGridMenuCommand.createEvent,
					{ entityTypeName: BX.CrmEntityType.names.lead, entityId: 1065 }
				)" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Добавить событие</span></span><span title="Написать письмо" onclick="BX.CrmUIGridExtension.processMenuCommand(
						'CRM_LEAD_LIST_V12_MANAGER',
						BX.CrmUIGridMenuCommand.createActivity,
						{ typeId: BX.CrmActivityType.email, settings: { ownerID: 1065 } }
					)" class="menu-popup-item menu-popup-no-icon "><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Написать письмо</span></span><span title="Запланировать дело" class="menu-popup-item menu-popup-no-icon menu-popup-item-submenu"><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Запланировать</span></span><a title="Сделать предложение" class="menu-popup-item menu-popup-no-icon " href="/crm/type/7/details/0/?lead_id=1065"><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Сделать предложение</span></a><span class="popup-window-delimiter"></span><span title="Запустить новый бизнес-процесс" class="menu-popup-item menu-popup-no-icon menu-popup-item-submenu"><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Новый бизнес-процесс</span></span><span title="Дополнительные возможности из каталога приложений" class="menu-popup-item menu-popup-no-icon menu-popup-item-submenu"><span class="menu-popup-item-icon"></span><span class="menu-popup-item-text">Битрикс24.Маркет</span></span></div></div></div><div class="popup-window-angly popup-window-angly-left" style="top: 10px;"><div class="popup-window-angly--arrow"></div></div></div>