<?php
$delFields=[
  "Стоимость объекта" =>"xy", 
  "Номер помещения"=>"xy", 
  "Тип недвижимости" =>"xy", 
  "Стадия объекта" =>"xy", 
  "ID ЖК"=>"xy", 
  "ID Здания"=>"xy", 
  "ID Секции"=>"xy", 
  //"Тип операции"=>"xy",
  "Размер комиссия в процентах"=>"xy",
  "Площадь участка (в сотках)"=>"xy",
  "Кадастровый номер"=>"xy",
  "Кадастровый номер земельного участка"=>"xy",
"Адрес"=>"xy", 
    "Широта"=>"xy", 
    "Долгота"=>"xy", 
    "Субъект федерации"=>"xy", 
    "Населенный пункт"=>"xy", 
    "Район"=>"xy", 
    "Улица"=>"xy",
    "Номер дома"=>"xy", 
    "ID Заявки"=>"xy", 
    "Ответственный"=>"xy", 
    "Стадия сделки"=>"xy", 
    "Тип сделки"=>"xy", 
    "Тип субъекта федерации"=>"xy", 
    "Тип населенного пункта"=>"xy", 
    "Тип улицы"=>"xy", 
   "Район региона"=>"xy", 
   "Контакт"=>"xy", 
   "Номер в парсинге"=>"xy", 
   "Название объявления"=>"xy", 
   "Субъект федерации" =>"xy",
   "Этаж" =>"xy",
   "Этажность" =>"xy",
   "Количество комнат" =>"xy",
   "Общая площадь" =>"xy",
   "Площадь кухни" =>"xy",
   "Район региона" =>"xy",
   "Населенный пункт" =>"xy",
   "Улица" =>"xy",
   "Номер дома" =>"xy",
   "Состояние" =>"xy",

  ];
  
$premises_fields = [
    'Квартира' => [
        'CS_FLOOR',
        'CS_NUMBER_OF_FLOORS',
        'CS_ROOMS',
        'CS_TOTAL_AREA',
        'CS_LIVE_AREA',
        'CS_KITCHEN_AREA',
        'CS_ROOMS_TYPE',
        'CS_WC_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_NEIGH_ROOMS',
        'CS_ANGLE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_WINDOWS_DIR',
        'CS_CEILING_HIGHT',
    ],
    'Комната' => [
        'CS_FLOOR',
        'CS_NUMBER_OF_FLOORS',
        'CS_TOTAL_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_ANGLE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_WINDOWS_DIR',
        'CS_CEILING_HIGHT',
    ],
    'Дом' => [
        'CS_NUMBER_OF_FLOORS',
        'CS_ROOMS',
        'CS_TOTAL_AREA',
        'CS_LIVE_AREA',
        'CS_KITCHEN_AREA',
        'CS_WC_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_NEIGH_ROOMS',
        'CS_ANGLE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_PLOT_AREA',
        'CS_PLOT_CAT',
        'CS_PLOT_PERMITTED_TYPES',
        'CS_CEILING_HIGHT',
    ],
    'Таунхаус' => [
        'CS_NUMBER_OF_FLOORS',
        'CS_ROOMS',
        'CS_TOTAL_AREA',
        'CS_LIVE_AREA',
        'CS_KITCHEN_AREA',
        'CS_WC_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_NEIGH_ROOMS',
        'CS_ANGLE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_PLOT_AREA',
        'CS_PLOT_CAT',
        'CS_PLOT_PERMITTED_TYPES',
        'CS_CEILING_HIGHT',
    ],
    'Дача' => [
        'CS_NUMBER_OF_FLOORS',
        'CS_ROOMS',
        'CS_TOTAL_AREA',
        'CS_LIVE_AREA',
        'CS_KITCHEN_AREA',
        'CS_WC_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_NEIGH_ROOMS',
        'CS_ANGLE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_PLOT_AREA',
        'CS_PLOT_CAT',
        'CS_PLOT_PERMITTED_TYPES',
        'CS_CEILING_HIGHT',
    ],
    'Коттедж' => [
        'CS_NUMBER_OF_FLOORS',
        'CS_ROOMS',
        'CS_TOTAL_AREA',
        'CS_LIVE_AREA',
        'CS_KITCHEN_AREA',
        'CS_WC_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_NEIGH_ROOMS',
        'CS_ANGLE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_PLOT_AREA',
        'CS_PLOT_CAT',
        'CS_PLOT_PERMITTED_TYPES',
        'CS_CEILING_HIGHT',
    ],
    'Участок' => [
        'CS_PLOT_AREA',
        'CS_PLOT_CAT',
        'CS_PLOT_PERMITTED_TYPES',
    ],
    'Коммерческий' => [
        'CS_FLOOR',
        'CS_NUMBER_OF_FLOORS',
        'CS_TOTAL_AREA',
        'CS_BUILDING_YEAR',
        'CS_ELEVATORS',
        'CS_HOUSE_TYPE',
        'CS_HEATING',
        'CS_HOT_WATER',
        'CS_WATER',
        'CS_GAS',
        'CS_ELECTRICITY',
        'CS_SEWAGE',
        'CS_CONDITION',
        'CS_WC',
        'CS_WINDOWS_TYPE',
        'CS_CEILING_HIGHT',
        'CS_SECURITY',
        'CS_OBJECT_CLASS',
        'CS_VENTILATION_TYPE',
        'CS_CONDITIONING_TYPE',
        'CS_EXTINGUISHING_SYSTEM',
        'CS_APPOINTMENT',
        'CS_TYPE_BUSINESS',
    ],
    'Гараж/паркинг' => [
        'CS_TOTAL_AREA',
        'CS_TYPE_PARKING',
    ]
    ];

$premises_fields_pars = [
    'Квартира' => [
    
        'UF_CS_PARSING_FLOOR',
        'UF_CS_PARSING_FLOORALL',
        'UF_CS_PARSING_ROOMS',
       'UF_CS_PARSING_TOTAL_AREA',
        'UF_CS_PARSING_LIVE_AREA',
        'UF_CS_PARSING_KITCHEN_AREA',
      'UF_CS_PARSING_BUILD_YEAR',
       'UF_CS_PARSING_ELEVATOR',
        'UF_CS_PARSING_HOUSE_TYPE',
       'UF_CS_PARSING_HEIGHT',
       'UF_CS_PARSING_GORYACHAYA_VODA',
        'UF_CS_PARSING_WATER',
      'UF_CS_PARSING_GAS',
       'UF_CS_PARSING_ELECTRICITY',
        'UF_CS_PARSING_SEWAGE',
        'UF_CS_PARSING_NEIGH_ROOMS',
        'UF_CS_PARSING_ANGLE',
       'UF_CS_PARSING_CONDITION',
        'UF_CS_PARSING_WC',
       'UF_CS_PARSING_WINDOWS_MAT',
       'UF_CS_PARSING_WINDOWS_DIR',
    ]
    ];

    $namePars= [
        
            'UF_CS_PARSING_FLOOR' => "Этаж",
            'UF_CS_PARSING_FLOORALL' => "Этажность",
            'UF_CS_PARSING_ROOMS' => "Количество комнат",
           'UF_CS_PARSING_TOTAL_AREA' => "Общая площадь",
            'UF_CS_PARSING_LIVE_AREA' => "Жилая площадь",
            'UF_CS_PARSING_KITCHEN_AREA' => "Площадь кухни",
          'UF_CS_PARSING_BUILD_YEAR' => "Год постройки",
           'UF_CS_PARSING_ELEVATOR' => "",
            'UF_CS_PARSING_HOUSE_TYPE' => "Тип здания",
           'UF_CS_PARSING_HEIGHT' => "Отопление",
           'UF_CS_PARSING_GORYACHAYA_VODA' => "Горячая вода",
            'UF_CS_PARSING_WATER' => "Вода",
          'UF_CS_PARSING_GAS' => "Газ",
           'UF_CS_PARSING_ELECTRICITY' => "Электричество",
            'UF_CS_PARSING_SEWAGE' => "",
            'UF_CS_PARSING_NEIGH_ROOMS' => "Смежные комнаты",
            'UF_CS_PARSING_ANGLE' => "",
           'UF_CS_PARSING_CONDITION' => "",
            'UF_CS_PARSING_WC' => "Сан.узел",
           'UF_CS_PARSING_WINDOWS_MAT' => "Материал окон",
           'UF_CS_PARSING_WINDOWS_DIR' => "Направление окон",
    ];