;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkBabelHelpers:function(){return window.babelHelpers},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://city.brokci.ru/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"38","sec":"gw3gjz","lang":"ru","address":"https:\/\/city.brokci.ru","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":"5"}},"data":{"language":"ru","design":{"style":"modern","dark":true,"shadow":true,"font":{"uri":"https:\/\/fonts.googleapis.com\/css?family=Open+Sans","family":"Open Sans"},"border":{"bottom":true,"top":false,"left":false,"right":false},"color":{"primary":"#0f83ffff","primaryText":"#f4f1f1ff","text":"#ffffffff","background":"#282d30ff","fieldBorder":"#ffffff19","fieldBackground":"#00000000","fieldFocusBackground":"#00000000"}},"title":"","desc":"","buttonCaption":"\u0416\u0434\u0443 \u0437\u0432\u043e\u043d\u043a\u0430","useSign":false,"date":{"dateFormat":"DD.MM.YYYY","dateTimeFormat":"DD.MM.YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"RUB","title":"\u0420\u0443\u0431\u043b\u044c","format":"# \u0440\u0443\u0431."},"fields":[{"id":"LEAD_COMPANY_TITLE","name":"LEAD_COMPANY_TITLE","label":"\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438","visible":true,"required":false,"multiple":false,"type":"company-name","placeholder":null,"value":"","items":[],"bigPic":false},{"id":"LEAD_NAME","name":"LEAD_NAME","label":"\u041a\u0430\u043a \u043a \u0412\u0430\u043c \u043e\u0431\u0440\u0430\u0449\u0430\u0442\u044c\u0441\u044f?","visible":true,"required":true,"multiple":false,"type":"name","placeholder":null,"value":"","items":[],"bigPic":false},{"id":"LEAD_PHONE","name":"LEAD_PHONE","label":"\u0422\u0435\u043b\u0435\u0444\u043e\u043d","visible":true,"required":true,"multiple":true,"type":"phone","placeholder":null,"value":"+7","items":[],"bigPic":false},{"id":"LEAD_EMAIL","name":"LEAD_EMAIL","label":"E-mail","visible":true,"required":false,"multiple":false,"type":"email","placeholder":null,"value":"","items":[],"bigPic":false}],"agreements":[],"dependencies":[],"recaptcha":{"use":false}}},"resources":{"app":"https:\/\/city.brokci.ru\/upload\/crm\/form\/app.js","polyfill":"https:\/\/city.brokci.ru\/upload\/crm\/form\/polyfill.js"}});
})();


})();