;(function () {
;(function () {
(function(){if(!window.b24form){window.b24form=function(e){b24form.forms=b24form.forms||[];b24form.forms.push(e);if(e.ref&&b24form.Loader&&!this.loaded){this.loaded=true;b24form.Loader.loadJs(e.ref,true)}}}if(window.b24form.Loader){return}function e(){this.requested=false;this.queue=[]}e.prototype={run:function(e){e=e||{};var o=e.resources||{};this.queue.push(e.form);if(!this.requested){var t=this.loadApp.bind(this,o.app);this.requested=true;if(o.polyfill&&!this.checkPolyfills()){this.loadJs(o.polyfill,true,t)}else{t()}}this.loadForms()},loadApp:function(e){if(!e){return}window.b24form.App?this.loadForms():this.loadJs(e,true,this.loadForms.bind(this))},loadForms:function(){if(!this.checkPolyfills()){return}if(!window.b24form.App){return}var e=this.queue;this.queue=[];e.forEach(this.loadForm,this)},loadForm:function(e){b24form.App.initFormScript24(e)},checkBabelHelpers:function(){return window.babelHelpers},checkPolyfills:function(){return window.fetch&&window.Request&&window.Response&&window.Promise&&Object.assign&&Array.prototype.find&&Array.prototype.includes},loadJs:function(e,o,t){var i=document.createElement("SCRIPT");i.setAttribute("type","text/javascript");i.setAttribute("async","");if(o){i.setAttribute("src",e+"?"+(Date.now()/864e5|0));if(t){i.onload=t}this.appendToHead(i)}else{i.appendChild(document.createTextNode(e));this.appendToHead(i)}},appendToHead:function(e){(document.getElementsByTagName("head")[0]||document.documentElement).appendChild(e)}};window.b24form.Loader=new e})();
//# sourceMappingURL=https://city.brokci.ru/bitrix/js/crm/site/form/embed/unit/script.map.js

window.b24form.Loader.run({"form":{"id":"23","sec":"m146ml","lang":"ru","address":"https:\/\/city.brokci.ru","views":{"click":{"type":"panel","position":"right","vertical":"bottom"},"auto":{"type":"popup","position":"center","vertical":"bottom","delay":5}},"data":{"language":"ru","design":{"shadow":true,"border":{"bottom":true},"color":{"primary":"#00AEEF","primaryText":"#FFFFFF","text":"#000000","background":"#FFFFFF","fieldBorder":"#00000019","fieldBackground":"#00000014","fieldFocusBackground":"#ffffffff"}},"title":"\u043d\u043e\u0432\u044b\u0439 \u043e\u0431\u044a\u0435\u043a\u0442","desc":"","buttonCaption":"\u041e\u0442\u043f\u0440\u0430\u0432\u0438\u0442\u044c","useSign":true,"date":{"dateFormat":"DD.MM.YYYY","dateTimeFormat":"DD.MM.YYYY HH:MI:SS","sundayFirstly":false},"currency":{"code":"RUB","title":"\u0420\u0443\u0431\u043b\u044c","format":"# \u0440\u0443\u0431."},"fields":[{"id":"DEAL_TITLE","name":"DEAL_TITLE","label":"\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435","visible":true,"required":false,"multiple":false,"type":"string","placeholder":"","value":"","items":[],"bigPic":false},{"id":"DEAL_UF_CRM_1472038962","name":"DEAL_UF_CRM_1472038962","label":"\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438","visible":true,"required":false,"multiple":false,"type":"file","placeholder":null,"value":null,"items":[],"bigPic":false}],"agreements":[],"dependencies":[],"recaptcha":{"use":false}}},"resources":{"app":"https:\/\/city.brokci.ru\/upload\/crm\/17d\/17de68c52ea71209654aa1c84910e296.js","polyfill":"https:\/\/city.brokci.ru\/upload\/crm\/c28\/c28c6fa95f324a078ebb7812e6751e60.js"}});
})();


})();